__title__ = "bot"
__description__ = "An instagram bot"
__url__ = "https://github.com/mrsumanbiswas/insta-bot"
__version__ = "0.00.1"
__author__ = "Suman Biswas"
__author_email__ = "mrsumanbiswas0@gmail.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2022 mrsumanbiswas"